# frozen_string_literal: true

module Types
  class SearchType < Types::BaseObject
    description 'Result object, they can be a: Car, Helicopter, Motorbike, Plane and Ship type.'
    field :uuid, ID, null: false
    field :slug, String, description: 'Autogenerated field.'
    field :searchable_type, String, description: 'Record class type: car, helicopter, motorbike, plane and ship'
    field :content, String
  end
end
